// Merchant Orientation Codes (MCC) for US
// Stripe requires this info to comply with US legistlation
// This data is extracted from https://stripe.com/docs/issuing/authorizations/categories

// prettier-ignore
const merchantOrientationCodes = [
  { "mcc": "7623", "label": "A/C, Refrigeration Repair", "Orientation": "ac_refrigeration_repair" },
  { "mcc": "8931", "label": "Accounting/Bookkeeping Services", "Orientation": "accounting_bookkeeping_services" },
  { "mcc": "7311", "label": "Advertising Services", "Orientation": "advertising_services" },
  { "mcc": "0763", "label": "Agricultural Cooperative", "Orientation": "agricultural_cooperative" },
  { "mcc": "4511", "label": "Airlines, Air Carriers", "Orientation": "airlines_air_carriers" },
  { "mcc": "4582", "label": "Airports, Flying Fields", "Orientation": "airports_flying_fields" },
  { "mcc": "4119", "label": "Ambulance Services", "Orientation": "ambulance_services" },
  { "mcc": "7996", "label": "Amusement Parks/Carnivals", "Orientation": "amusement_parks_carnivals" },
  { "mcc": "5937", "label": "Antique Reproductions", "Orientation": "antique_reproductions" },
  { "mcc": "5932", "label": "Antique Shops", "Orientation": "antique_shops" },
  { "mcc": "7998", "label": "Aquariums", "Orientation": "aquariums" },
  { "mcc": "8911", "label": "Architectural/Surveying Services", "Orientation": "architectural_surveying_services" },
  { "mcc": "5971", "label": "Art Dealers and Galleries", "Orientation": "art_dealers_and_galleries" },
  { "mcc": "5970", "label": "Artists Supply and Craft Shops", "Orientation": "artists_supply_and_craft_shops" },
  { "mcc": "7531", "label": "Auto Body Repair Shops", "Orientation": "auto_body_repair_shops" },
  { "mcc": "7535", "label": "Auto Paint Shops", "Orientation": "auto_paint_shops" },
  { "mcc": "7538", "label": "Auto Service Shops", "Orientation": "auto_service_shops" },
  { "mcc": "5531", "label": "Auto and Home Supply Stores", "Orientation": "auto_and_home_supply_stores" },
  { "mcc": "6011", "label": "Automated Cash Disburse", "Orientation": "automated_cash_disburse" },
  { "mcc": "5542", "label": "Automated Fuel Dispensers", "Orientation": "automated_fuel_dispensers" },
  { "mcc": "8675", "label": "Automobile Associations", "Orientation": "automobile_associations" },
  { "mcc": "5533", "label": "Automotive Parts and Accessories Stores", "Orientation": "automotive_parts_and_accessories_stores" },
  { "mcc": "5532", "label": "Automotive Tire Stores", "Orientation": "automotive_tire_stores" },
  { "mcc": "9223", "label": "Bail and Bond Payments (payment to the surety for the bond, not the actual bond paid to the government agency)", "Orientation": "bail_and_bond_payments" },
  { "mcc": "5462", "label": "Bakeries", "Orientation": "bakeries" },
  { "mcc": "7929", "label": "Bands, Orchestras", "Orientation": "bands_orchestras" },
  { "mcc": "7230", "label": "Barber and Beauty Shops", "Orientation": "barber_and_beauty_shops" },
  { "mcc": "7995", "label": "Betting/Casino Gambling", "Orientation": "betting_casino_gambling" },
  { "mcc": "5940", "label": "Bicycle Shops", "Orientation": "bicycle_shops" },
  { "mcc": "7932", "label": "Billiard/Pool Establishments", "Orientation": "billiard_pool_establishments" },
  { "mcc": "5551", "label": "Boat Dealers", "Orientation": "boat_dealers" },
  { "mcc": "4457", "label": "Boat Rentals and Leases", "Orientation": "boat_rentals_and_leases" },
  { "mcc": "5942", "label": "Book Stores", "Orientation": "book_stores" },
  { "mcc": "5192", "label": "Books, Periodicals, and Newspapers", "Orientation": "books_periodicals_and_newspapers" },
  { "mcc": "7933", "label": "Bowling Alleys", "Orientation": "bowling_alleys" },
  { "mcc": "4131", "label": "Bus Lines", "Orientation": "bus_lines" },
  { "mcc": "8244", "label": "Business/Secretarial Schools", "Orientation": "business_secretarial_schools" },
  { "mcc": "7278", "label": "Buying/Shopping Services", "Orientation": "buying_shopping_services" },
  { "mcc": "4899", "label": "Cable, Satellite, and Other Pay Television and Radio", "Orientation": "cable_satellite_and_other_pay_television_and_radio" },
  { "mcc": "5946", "label": "Camera and Photographic Supply Stores", "Orientation": "camera_and_photographic_supply_stores" },
  { "mcc": "5441", "label": "Candy, Nut, and Confectionery Stores", "Orientation": "candy_nut_and_confectionery_stores" },
  { "mcc": "7512", "label": "Car Rental Agencies", "Orientation": "car_rental_agencies" },
  { "mcc": "7542", "label": "Car Washes", "Orientation": "car_washes" },
  { "mcc": "5511", "label": "Car and Truck Dealers (New & Used) Sales, Service, Repairs Parts and Leasing", "Orientation": "car_and_truck_dealers_new_used" },
  { "mcc": "5521", "label": "Car and Truck Dealers (Used Only) Sales, Service, Repairs Parts and Leasing", "Orientation": "car_and_truck_dealers_used_only" },
  { "mcc": "1750", "label": "Carpentry Services", "Orientation": "carpentry_services" },
  { "mcc": "7217", "label": "Carpet/Upholstery Cleaning", "Orientation": "carpet_upholstery_cleaning" },
  { "mcc": "5811", "label": "Caterers", "Orientation": "caterers" },
  { "mcc": "8398", "label": "Charitable and Social Service Organizations - Fundraising", "Orientation": "charitable_and_social_service_organizations_fundraising" },
  { "mcc": "5169", "label": "Chemicals and Allied Products (Not Elsewhere Classified)", "Orientation": "chemicals_and_allied_products" },
  { "mcc": "5641", "label": "Chidrens and Infants Wear Stores", "Orientation": "chidrens_and_infants_wear_stores" },
  { "mcc": "8351", "label": "Child Care Services", "Orientation": "child_care_services" },
  { "mcc": "8049", "label": "Chiropodists, Podiatrists", "Orientation": "chiropodists_podiatrists" },
  { "mcc": "8041", "label": "Chiropractors", "Orientation": "chiropractors" },
  { "mcc": "5993", "label": "Cigar Stores and Stands", "Orientation": "cigar_stores_and_stands" },
  { "mcc": "8641", "label": "Civic, Social, Fraternal Associations", "Orientation": "civic_social_fraternal_associations" },
  { "mcc": "7349", "label": "Cleaning and Maintenance", "Orientation": "cleaning_and_maintenance" },
  { "mcc": "7296", "label": "Clothing Rental", "Orientation": "clothing_rental" },
  { "mcc": "8220", "label": "Colleges, Universities", "Orientation": "colleges_universities" },
  { "mcc": "5046", "label": "Commercial Equipment (Not Elsewhere Classified)", "Orientation": "commercial_equipment" },
  { "mcc": "5139", "label": "Commercial Footwear", "Orientation": "commercial_footwear" },
  { "mcc": "7333", "label": "Commercial Photography, Art and Graphics", "Orientation": "commercial_photography_art_and_graphics" },
  { "mcc": "4111", "label": "Commuter Transport, Ferries", "Orientation": "commuter_transport_and_ferries" },
  { "mcc": "4816", "label": "Computer Network Services", "Orientation": "computer_network_services" },
  { "mcc": "7372", "label": "Computer Programming", "Orientation": "computer_programming" },
  { "mcc": "7379", "label": "Computer Repair", "Orientation": "computer_repair" },
  { "mcc": "5734", "label": "Computer Software Stores", "Orientation": "computer_software_stores" },
  { "mcc": "5045", "label": "Computers, Peripherals, and Software", "Orientation": "computers_peripherals_and_software" },
  { "mcc": "1771", "label": "Concrete Work Services", "Orientation": "concrete_work_services" },
  { "mcc": "5039", "label": "Construction Materials (Not Elsewhere Classified)", "Orientation": "construction_materials" },
  { "mcc": "7392", "label": "Consulting, Public Relations", "Orientation": "consulting_public_relations" },
  { "mcc": "8241", "label": "Correspondence Schools", "Orientation": "correspondence_schools" },
  { "mcc": "5977", "label": "Cosmetic Stores", "Orientation": "cosmetic_stores" },
  { "mcc": "7277", "label": "Counseling Services", "Orientation": "counseling_services" },
  { "mcc": "7997", "label": "Country Clubs", "Orientation": "country_clubs" },
  { "mcc": "4215", "label": "Courier Services", "Orientation": "courier_services" },
  { "mcc": "9211", "label": "Court Costs, Including Alimony and Child Support - Courts of Law", "Orientation": "court_costs" },
  { "mcc": "7321", "label": "Credit Reporting Agencies", "Orientation": "credit_reporting_agencies" },
  { "mcc": "4411", "label": "Cruise Lines", "Orientation": "cruise_lines" },
  { "mcc": "5451", "label": "Dairy Products Stores", "Orientation": "dairy_products_stores" },
  { "mcc": "7911", "label": "Dance Hall, Studios, Schools", "Orientation": "dance_hall_studios_schools" },
  { "mcc": "7273", "label": "Dating/Escort Services", "Orientation": "dating_escort_services" },
  { "mcc": "8021", "label": "Dentists, Orthodontists", "Orientation": "dentists_orthodontists" },
  { "mcc": "5311", "label": "Department Stores", "Orientation": "department_stores" },
  { "mcc": "7393", "label": "Detective Agencies", "Orientation": "detective_agencies" },
  { "mcc": "5964", "label": "Direct Marketing - Catalog Merchant", "Orientation": "direct_marketing_catalog_merchant" },
  { "mcc": "5965", "label": "Direct Marketing - Combination Catalog and Retail Merchant", "Orientation": "direct_marketing_combination_catalog_and_retail_merchant" },
  { "mcc": "5967", "label": "Direct Marketing - Inbound Telemarketing", "Orientation": "direct_marketing_inbound_telemarketing" },
  { "mcc": "5960", "label": "Direct Marketing - Insurance Services", "Orientation": "direct_marketing_insurance_services" },
  { "mcc": "5969", "label": "Direct Marketing - Other", "Orientation": "direct_marketing_other" },
  { "mcc": "5966", "label": "Direct Marketing - Outbound Telemarketing", "Orientation": "direct_marketing_outbound_telemarketing" },
  { "mcc": "5968", "label": "Direct Marketing - Subscription", "Orientation": "direct_marketing_subscription" },
  { "mcc": "5962", "label": "Direct Marketing - Travel", "Orientation": "direct_marketing_travel" },
  { "mcc": "5310", "label": "Discount Stores", "Orientation": "discount_stores" },
  { "mcc": "8011", "label": "Doctors", "Orientation": "doctors" },
  { "mcc": "5963", "label": "Door-To-Door Sales", "Orientation": "door_to_door_sales" },
  { "mcc": "5714", "label": "Drapery, Window Covering, and Upholstery Stores", "Orientation": "drapery_window_covering_and_upholstery_stores" },
  { "mcc": "5813", "label": "Drinking Places", "Orientation": "drinking_places" },
  { "mcc": "5912", "label": "Drug Stores and Pharmacies", "Orientation": "drug_stores_and_pharmacies" },
  { "mcc": "5122", "label": "Drugs, Drug Proprietaries, and Druggist Sundries", "Orientation": "drugs_drug_proprietaries_and_druggist_sundries" },
  { "mcc": "7216", "label": "Dry Cleaners", "Orientation": "dry_cleaners" },
  { "mcc": "5099", "label": "Durable Goods (Not Elsewhere Classified)", "Orientation": "durable_goods" },
  { "mcc": "5309", "label": "Duty Free Stores", "Orientation": "duty_free_stores" },
  { "mcc": "5812", "label": "Eating Places, Restaurants", "Orientation": "eating_places_restaurants" },
  { "mcc": "8299", "label": "Educational Services", "Orientation": "educational_services" },
  { "mcc": "5997", "label": "Electric Razor Stores", "Orientation": "electric_razor_stores" },
  { "mcc": "5065", "label": "Electrical Parts and Equipment", "Orientation": "electrical_parts_and_equipment" },
  { "mcc": "1731", "label": "Electrical Services", "Orientation": "electrical_services" },
  { "mcc": "7622", "label": "Electronics Repair Shops", "Orientation": "electronics_repair_shops" },
  { "mcc": "5732", "label": "Electronics Stores", "Orientation": "electronics_stores" },
  { "mcc": "8211", "label": "Elementary, Secondary Schools", "Orientation": "elementary_secondary_schools" },
  { "mcc": "7361", "label": "Employment/Temp Agencies", "Orientation": "employment_temp_agencies" },
  { "mcc": "7394", "label": "Equipment Rental", "Orientation": "equipment_rental" },
  { "mcc": "7342", "label": "Exterminating Services", "Orientation": "exterminating_services" },
  { "mcc": "5651", "label": "Family Clothing Stores", "Orientation": "family_clothing_stores" },
  { "mcc": "5814", "label": "Fast Food Restaurants", "Orientation": "fast_food_restaurants" },
  { "mcc": "6012", "label": "Financial Institutions", "Orientation": "financial_institutions" },
  { "mcc": "9222", "label": "Fines - Government Administrative Entities", "Orientation": "fines_government_administrative_entities" },
  { "mcc": "5718", "label": "Fireplace, Fireplace Screens, and Accessories Stores", "Orientation": "fireplace_fireplace_screens_and_accessories_stores" },
  { "mcc": "5713", "label": "Floor Covering Stores", "Orientation": "floor_covering_stores" },
  { "mcc": "5992", "label": "Florists", "Orientation": "florists" },
  { "mcc": "5193", "label": "Florists Supplies, Nursery Stock, and Flowers", "Orientation": "florists_supplies_nursery_stock_and_flowers" },
  { "mcc": "5422", "label": "Freezer and Locker Meat Provisioners", "Orientation": "freezer_and_locker_meat_provisioners" },
  { "mcc": "5983", "label": "Fuel Dealers (Non Automotive)", "Orientation": "fuel_dealers_non_automotive" },
  { "mcc": "7261", "label": "Funeral Services, Crematories", "Orientation": "funeral_services_crematories" },
  { "mcc": "7641", "label": "Furniture Repair, Refinishing", "Orientation": "furniture_repair_refinishing" },
  { "mcc": "5712", "label": "Furniture, Home Furnishings, and Equipment Stores, Except Appliances", "Orientation": "furniture_home_furnishings_and_equipment_stores_except_appliances" },
  { "mcc": "5681", "label": "Furriers and Fur Shops", "Orientation": "furriers_and_fur_shops" },
  { "mcc": "1520", "label": "General Services", "Orientation": "general_services" },
  { "mcc": "5947", "label": "Gift, Card, Novelty, and Souvenir Shops", "Orientation": "gift_card_novelty_and_souvenir_shops" },
  { "mcc": "5231", "label": "Glass, Paint, and Wallpaper Stores", "Orientation": "glass_paint_and_wallpaper_stores" },
  { "mcc": "5950", "label": "Glassware, Crystal Stores", "Orientation": "glassware_crystal_stores" },
  { "mcc": "7992", "label": "Golf Courses - Public", "Orientation": "golf_courses_public" },
  { "mcc": "9399", "label": "Government Services (Not Elsewhere Classified)", "Orientation": "government_services" },
  { "mcc": "5411", "label": "Grocery Stores, Supermarkets", "Orientation": "grocery_stores_supermarkets" },
  { "mcc": "5251", "label": "Hardware Stores", "Orientation": "hardware_stores" },
  { "mcc": "5072", "label": "Hardware, Equipment, and Supplies", "Orientation": "hardware_equipment_and_supplies" },
  { "mcc": "7298", "label": "Health and Beauty Spas", "Orientation": "health_and_beauty_spas" },
  { "mcc": "5975", "label": "Hearing Aids Sales and Supplies", "Orientation": "hearing_aids_sales_and_supplies" },
  { "mcc": "1711", "label": "Heating, Plumbing, A/C", "Orientation": "heating_plumbing_a_c" },
  { "mcc": "5945", "label": "Hobby, Toy, and Game Shops", "Orientation": "hobby_toy_and_game_shops" },
  { "mcc": "5200", "label": "Home Supply Warehouse Stores", "Orientation": "home_supply_warehouse_stores" },
  { "mcc": "8062", "label": "Hospitals", "Orientation": "hospitals" },
  { "mcc": "7011", "label": "Hotels, Motels, and Resorts", "Orientation": "hotels_motels_and_resorts" },
  { "mcc": "5722", "label": "Household Appliance Stores", "Orientation": "household_appliance_stores" },
  { "mcc": "5085", "label": "Industrial Supplies (Not Elsewhere Classified)", "Orientation": "industrial_supplies" },
  { "mcc": "7375", "label": "Information Retrieval Services", "Orientation": "information_retrieval_services" },
  { "mcc": "6399", "label": "Insurance - Default", "Orientation": "insurance_default" },
  { "mcc": "6300", "label": "Insurance Underwriting, Premiums", "Orientation": "insurance_underwriting_premiums" },
  { "mcc": "9950", "label": "Intra-Company Purchases", "Orientation": "intra_company_purchases" },
  { "mcc": "5944", "label": "Jewelry Stores, Watches, Clocks, and Silverware Stores", "Orientation": "jewelry_stores_watches_clocks_and_silverware_stores" },
  { "mcc": "0780", "label": "Landscaping Services", "Orientation": "landscaping_services" },
  { "mcc": "7211", "label": "Laundries", "Orientation": "laundries" },
  { "mcc": "7210", "label": "Laundry, Cleaning Services", "Orientation": "laundry_cleaning_services" },
  { "mcc": "8111", "label": "Legal Services, Attorneys", "Orientation": "legal_services_attorneys" },
  { "mcc": "5948", "label": "Luggage and Leather Goods Stores", "Orientation": "luggage_and_leather_goods_stores" },
  { "mcc": "5211", "label": "Lumber, Building Materials Stores", "Orientation": "lumber_building_materials_stores" },
  { "mcc": "6010", "label": "Manual Cash Disburse", "Orientation": "manual_cash_disburse" },
  { "mcc": "4468", "label": "Marinas, Service and Supplies", "Orientation": "marinas_service_and_supplies" },
  { "mcc": "1740", "label": "Masonry, Stonework, and Plaster", "Orientation": "masonry_stonework_and_plaster" },
  { "mcc": "7297", "label": "Massage Parlors", "Orientation": "massage_parlors" },
  { "mcc": "8099", "label": "Medical Services", "Orientation": "medical_services" },
  { "mcc": "8071", "label": "Medical and Dental Labs", "Orientation": "medical_and_dental_labs" },
  { "mcc": "5047", "label": "Medical, Dental, Ophthalmic, and Hospital Equipment and Supplies", "Orientation": "medical_dental_ophthalmic_and_hospital_equipment_and_supplies" },
  { "mcc": "8699", "label": "Membership Organizations", "Orientation": "membership_organizations" },
  { "mcc": "5611", "label": "Mens and Boys Clothing and Accessories Stores", "Orientation": "mens_and_boys_clothing_and_accessories_stores" },
  { "mcc": "5691", "label": "Mens, Womens Clothing Stores", "Orientation": "mens_womens_clothing_stores" },
  { "mcc": "5051", "label": "Metal Service Centers", "Orientation": "metal_service_centers" },
  { "mcc": "5699", "label": "Miscellaneous Apparel and Accessory Shops", "Orientation": "miscellaneous_apparel_and_accessory_shops" },
  { "mcc": "5599", "label": "Miscellaneous Auto Dealers", "Orientation": "miscellaneous_auto_dealers" },
  { "mcc": "7399", "label": "Miscellaneous Business Services", "Orientation": "miscellaneous_business_services" },
  { "mcc": "5499", "label": "Miscellaneous Food Stores - Convenience Stores and Specialty Markets", "Orientation": "miscellaneous_food_stores" },
  { "mcc": "5399", "label": "Miscellaneous General Merchandise", "Orientation": "miscellaneous_general_merchandise" },
  { "mcc": "7299", "label": "Miscellaneous General Services", "Orientation": "miscellaneous_general_services" },
  { "mcc": "5719", "label": "Miscellaneous Home Furnishing Specialty Stores", "Orientation": "miscellaneous_home_furnishing_specialty_stores" },
  { "mcc": "2741", "label": "Miscellaneous Publishing and Printing", "Orientation": "miscellaneous_publishing_and_printing" },
  { "mcc": "7999", "label": "Miscellaneous Recreation Services", "Orientation": "miscellaneous_recreation_services" },
  { "mcc": "7699", "label": "Miscellaneous Repair Shops", "Orientation": "miscellaneous_repair_shops" },
  { "mcc": "5999", "label": "Miscellaneous Specialty Retail", "Orientation": "miscellaneous_specialty_retail" },
  { "mcc": "5271", "label": "Mobile Home Dealers", "Orientation": "mobile_home_dealers" },
  { "mcc": "7832", "label": "Motion Picture Theaters", "Orientation": "motion_picture_theaters" },
  { "mcc": "4214", "label": "Motor Freight Carriers and Trucking - Local and Long Distance, Moving and Storage Companies, and Local Delivery Services", "Orientation": "motor_freight_carriers_and_trucking" },
  { "mcc": "5592", "label": "Motor Homes Dealers", "Orientation": "motor_homes_dealers" },
  { "mcc": "5013", "label": "Motor Vehicle Supplies and New Parts", "Orientation": "motor_vehicle_supplies_and_new_parts" },
  { "mcc": "5571", "label": "Motorcycle Shops and Dealers", "Orientation": "motorcycle_shops_and_dealers" },
  { "mcc": "5561", "label": "Motorcycle Shops, Dealers", "Orientation": "motorcycle_shops_dealers" },
  { "mcc": "5733", "label": "Music Stores-Musical Instruments, Pianos, and Sheet Music", "Orientation": "music_stores_musical_instruments_pianos_and_sheet_music" },
  { "mcc": "5994", "label": "News Dealers and Newsstands", "Orientation": "news_dealers_and_newsstands" },
  { "mcc": "6051", "label": "Non-FI, Money Orders", "Orientation": "non_fi_money_orders" },
  { "mcc": "6540", "label": "Non-FI, Stored Value Card Purchase/Load", "Orientation": "non_fi_stored_value_card_purchase_load" },
  { "mcc": "5199", "label": "Nondurable Goods (Not Elsewhere Classified)", "Orientation": "nondurable_goods" },
  { "mcc": "5261", "label": "Nurseries, Lawn and Garden Supply Stores", "Orientation": "nurseries_lawn_and_garden_supply_stores" },
  { "mcc": "8050", "label": "Nursing/Personal Care", "Orientation": "nursing_personal_care" },
  { "mcc": "5021", "label": "Office and Commercial Furniture", "Orientation": "office_and_commercial_furniture" },
  { "mcc": "8043", "label": "Opticians, Eyeglasses", "Orientation": "opticians_eyeglasses" },
  { "mcc": "8042", "label": "Optometrists, Ophthalmologist", "Orientation": "optometrists_ophthalmologist" },
  { "mcc": "5976", "label": "Orthopedic Goods - Prosthetic Devices", "Orientation": "orthopedic_goods_prosthetic_devices" },
  { "mcc": "8031", "label": "Osteopaths", "Orientation": "osteopaths" },
  { "mcc": "5921", "label": "Package Stores-Beer, Wine, and Liquor", "Orientation": "package_stores_beer_wine_and_liquor" },
  { "mcc": "5198", "label": "Paints, Varnishes, and Supplies", "Orientation": "paints_varnishes_and_supplies" },
  { "mcc": "7523", "label": "Parking Lots, Garages", "Orientation": "parking_lots_garages" },
  { "mcc": "4112", "label": "Passenger Railways", "Orientation": "passenger_railways" },
  { "mcc": "5933", "label": "Pawn Shops", "Orientation": "pawn_shops" },
  { "mcc": "5995", "label": "Pet Shops, Pet Food, and Supplies", "Orientation": "pet_shops_pet_food_and_supplies" },
  { "mcc": "5172", "label": "Petroleum and Petroleum Products", "Orientation": "petroleum_and_petroleum_products" },
  { "mcc": "7395", "label": "Photo Developing", "Orientation": "photo_developing" },
  { "mcc": "7221", "label": "Photographic Studios", "Orientation": "photographic_studios" },
  { "mcc": "5044", "label": "Photographic, Photocopy, Microfilm Equipment, and Supplies", "Orientation": "photographic_photocopy_microfilm_equipment_and_supplies" },
  { "mcc": "7829", "label": "Picture/Video Production", "Orientation": "picture_video_production" },
  { "mcc": "5131", "label": "Piece Goods, Notions, and Other Dry Goods", "Orientation": "piece_goods_notions_and_other_dry_goods" },
  { "mcc": "5074", "label": "Plumbing, Heating Equipment, and Supplies", "Orientation": "plumbing_heating_equipment_and_supplies" },
  { "mcc": "8651", "label": "Political Organizations", "Orientation": "political_organizations" },
  { "mcc": "9402", "label": "Postal Services - Government Only", "Orientation": "postal_services_government_only" },
  { "mcc": "5094", "label": "Precious Stones and Metals, Watches and Jewelry", "Orientation": "precious_stones_and_metals_watches_and_jewelry" },
  { "mcc": "8999", "label": "Professional Services", "Orientation": "professional_services" },
  { "mcc": "4225", "label": "Public Warehousing and Storage - Farm Products, Refrigerated Goods, Household Goods, and Storage", "Orientation": "public_warehousing_and_storage" },
  { "mcc": "7338", "label": "Quick Copy, Repro, and Blueprint", "Orientation": "quick_copy_repro_and_blueprint" },
  { "mcc": "4011", "label": "Railroads", "Orientation": "railroads" },
  { "mcc": "6513", "label": "Real Estate Agents and Managers - Rentals", "Orientation": "real_estate_agents_and_managers_rentals" },
  { "mcc": "5735", "label": "Record Stores", "Orientation": "record_stores" },
  { "mcc": "7519", "label": "Recreational Vehicle Rentals", "Orientation": "recreational_vehicle_rentals" },
  { "mcc": "5973", "label": "Religious Goods Stores", "Orientation": "religious_goods_stores" },
  { "mcc": "8661", "label": "Religious Organizations", "Orientation": "religious_organizations" },
  { "mcc": "1761", "label": "Roofing/Siding, Sheet Metal", "Orientation": "roofing_siding_sheet_metal" },
  { "mcc": "7339", "label": "Secretarial Support Services", "Orientation": "secretarial_support_services" },
  { "mcc": "6211", "label": "Security Brokers/Dealers", "Orientation": "security_brokers_dealers" },
  { "mcc": "5541", "label": "Service Stations", "Orientation": "service_stations" },
  { "mcc": "5949", "label": "Sewing, Needlework, Fabric, and Piece Goods Stores", "Orientation": "sewing_needlework_fabric_and_piece_goods_stores" },
  { "mcc": "7251", "label": "Shoe Repair/Hat Cleaning", "Orientation": "shoe_repair_hat_cleaning" },
  { "mcc": "5661", "label": "Shoe Stores", "Orientation": "shoe_stores" },
  { "mcc": "7629", "label": "Small Appliance Repair", "Orientation": "small_appliance_repair" },
  { "mcc": "5598", "label": "Snowmobile Dealers", "Orientation": "snowmobile_dealers" },
  { "mcc": "1799", "label": "Special Trade Services", "Orientation": "special_trade_services" },
  { "mcc": "2842", "label": "Specialty Cleaning", "Orientation": "specialty_cleaning" },
  { "mcc": "5941", "label": "Sporting Goods Stores", "Orientation": "sporting_goods_stores" },
  { "mcc": "7032", "label": "Sporting/Recreation Camps", "Orientation": "sporting_recreation_camps" },
  { "mcc": "7941", "label": "Sports Clubs/Fields", "Orientation": "sports_clubs_fields" },
  { "mcc": "5655", "label": "Sports and Riding Apparel Stores", "Orientation": "sports_and_riding_apparel_stores" },
  { "mcc": "5972", "label": "Stamp and Coin Stores", "Orientation": "stamp_and_coin_stores" },
  { "mcc": "5111", "label": "Stationary, Office Supplies, Printing and Writing Paper", "Orientation": "stationary_office_supplies_printing_and_writing_paper" },
  { "mcc": "5943", "label": "Stationery Stores, Office, and School Supply Stores", "Orientation": "stationery_stores_office_and_school_supply_stores" },
  { "mcc": "5996", "label": "Swimming Pools Sales", "Orientation": "swimming_pools_sales" },
  { "mcc": "4723", "label": "TUI Travel - Germany", "Orientation": "t_ui_travel_germany" },
  { "mcc": "5697", "label": "Tailors, Alterations", "Orientation": "tailors_alterations" },
  { "mcc": "9311", "label": "Tax Payments - Government Agencies", "Orientation": "tax_payments_government_agencies" },
  { "mcc": "7276", "label": "Tax Preparation Services", "Orientation": "tax_preparation_services" },
  { "mcc": "4121", "label": "Taxicabs/Limousines", "Orientation": "taxicabs_limousines" },
  { "mcc": "4812", "label": "Telecommunication Equipment and Telephone Sales", "Orientation": "telecommunication_equipment_and_telephone_sales" },
  { "mcc": "4814", "label": "Telecommunication Services", "Orientation": "telecommunication_services" },
  { "mcc": "4821", "label": "Telegraph Services", "Orientation": "telegraph_services" },
  { "mcc": "5998", "label": "Tent and Awning Shops", "Orientation": "tent_and_awning_shops" },
  { "mcc": "8734", "label": "Testing Laboratories", "Orientation": "testing_laboratories" },
  { "mcc": "7922", "label": "Theatrical Ticket Agencies", "Orientation": "theatrical_ticket_agencies" },
  { "mcc": "7012", "label": "Timeshares", "Orientation": "timeshares" },
  { "mcc": "7534", "label": "Tire Retreading and Repair", "Orientation": "tire_retreading_and_repair" },
  { "mcc": "4784", "label": "Tolls/Bridge Fees", "Orientation": "tolls_bridge_fees" },
  { "mcc": "7991", "label": "Tourist Attractions and Exhibits", "Orientation": "tourist_attractions_and_exhibits" },
  { "mcc": "7549", "label": "Towing Services", "Orientation": "towing_services" },
  { "mcc": "7033", "label": "Trailer Parks, Campgrounds", "Orientation": "trailer_parks_campgrounds" },
  { "mcc": "4789", "label": "Transportation Services (Not Elsewhere Classified)", "Orientation": "transportation_services" },
  { "mcc": "4722", "label": "Travel Agencies, Tour Operators", "Orientation": "travel_agencies_tour_operators" },
  { "mcc": "7511", "label": "Truck StopIteration", "Orientation": "truck_stop_iteration" },
  { "mcc": "7513", "label": "Truck/Utility Trailer Rentals", "Orientation": "truck_utility_trailer_rentals" },
  { "mcc": "2791", "label": "Typesetting, Plate Making, and Related Services", "Orientation": "typesetting_plate_making_and_related_services" },
  { "mcc": "5978", "label": "Typewriter Stores", "Orientation": "typewriter_stores" },
  { "mcc": "9405", "label": "U.S. Federal Government Agencies or Departments", "Orientation": "u_s_federal_government_agencies_or_departments" },
  { "mcc": "5137", "label": "Uniforms, Commercial Clothing", "Orientation": "uniforms_commercial_clothing" },
  { "mcc": "5931", "label": "Used Merchandise and Secondhand Stores", "Orientation": "used_merchandise_and_secondhand_stores" },
  { "mcc": "4900", "label": "Utilities", "Orientation": "utilities" },
  { "mcc": "5331", "label": "Variety Stores", "Orientation": "variety_stores" },
  { "mcc": "0742", "label": "Veterinary Services", "Orientation": "veterinary_services" },
  { "mcc": "7993", "label": "Video Amusement Game Supplies", "Orientation": "video_amusement_game_supplies" },
  { "mcc": "7994", "label": "Video Game Arcades", "Orientation": "video_game_arcades" },
  { "mcc": "7841", "label": "Video Tape Rental Stores", "Orientation": "video_tape_rental_stores" },
  { "mcc": "8249", "label": "Vocational/Trade Schools", "Orientation": "vocational_trade_schools" },
  { "mcc": "7631", "label": "Watch/Jewelry Repair", "Orientation": "watch_jewelry_repair" },
  { "mcc": "7692", "label": "Welding Repair", "Orientation": "welding_repair" },
  { "mcc": "5300", "label": "Wholesale Clubs", "Orientation": "wholesale_clubs" },
  { "mcc": "5698", "label": "Wig and Toupee Stores", "Orientation": "wig_and_toupee_stores" },
  { "mcc": "4829", "label": "Wires, Money Orders", "Orientation": "wires_money_orders" },
  { "mcc": "5631", "label": "Womens Accessory and Specialty Shops", "Orientation": "womens_accessory_and_specialty_shops" },
  { "mcc": "5621", "label": "Womens Ready-To-Wear Stores", "Orientation": "womens_ready_to_wear_stores" },
  { "mcc": "5935", "label": "Wrecking and Salvage Yards", "Orientation": "wrecking_and_salvage_yards" },
];

export default merchantOrientationCodes;
